### ISSUE TITLE
Add test coverage for address in EthereumRPC

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/EthereumRPCSharp#20]
Based on https://github.com/ethers-io/ethers.js/blob/main/src.ts/_tests/test-address.ts

**Comment by giladkah** [comment]
@Arshia001, @juans-chainsafe 
Tests are great! so happy you're doing it. 
do we have a test coverage plan? 
Get it from 30%->40% , for example?

**Comment by juans-chainsafe** [comment]
> @Arshia001, @juans-chainsafe Tests are great! so happy you're doing it. do we have a test coverage plan? Get it from 30%->40% , for example?

Since I started adding tests 2 weeks ago we have 22% of test coverage
<img width="751" alt="Screenshot 2023-04-25 at 09 45 44" src="https://user-images.githubusercontent.com/104365141/234280503-abae39ba-9235-4fec-abf6-44bb5c2fc78e.png">

HTML report:
[test_coverage.html.zip](https://github.com/ChainSafe/EthereumRPCSharp/files/11322586/test_coverage.html.zip)

We didn't think with Mike a % of coverage, we prioritize what we though the most important coverage. But, in my opinion we should have at least 80% of coverage

**Comment by Arshia001** [comment]
I agree with @juans-chainsafe that we should maintain at least 80%. Making test coverage a merge gate is on the technical roadmap.

**Comment by giladkah** [comment]
Perfect 😍
